### ISSUE TITLE
Parse Error on "calc(env(safe-area-inset-bottom) * 3)"

### ISSUE THREAD

**Issue by MarvinXu** [cssnano/cssnano#578]
cssnano version: latest(4.0.5)
(I used to use version cssnano@3.10.0, and it works fine)

my css code:
```css
@supports (height: env(safe-area-inset-bottom)) {
  .footer {
    padding-bottom: calc(env(safe-area-inset-bottom) * 3) !important;
  }
}
```
error msg:
![image](https://user-images.githubusercontent.com/7382357/43777243-bf732e72-9a84-11e8-8a09-cdffdfee86cc.png)

**Comment by evilebottnawi** [comment]
@MarvinXu expected, you use non standard css, please move `cssnano` latest in postcss plugins.

**Comment by andyjansson** [comment]
Please refer to this: https://github.com/MoOx/reduce-css-calc/issues/34

**Comment by MarvinXu** [comment]
@evilebottnawi do u mean I should downgrade cssnano? but this seems to be a problem that should be solved anyhow

**Comment by evilebottnawi** [comment]
@MarvinXu you should put cssnano as last postcss plugin, cssnano works only with standard css

**Comment by andyjansson** [comment]
@evilebottnawi `env()` and `constant()` is an iPhone X-only feature. It's not standard, but it's not exactly made up either. Either way, the issue lies with reduce-css-calc.

**Comment by guylando** [comment]
FYI: I wrote a simple workaround in a comment in https://github.com/MoOx/reduce-css-calc/issues/34

**Comment by andyjansson** [comment]
I'll get to work on fixing this next week by moving the logic from `reduce-css-calc` to `postcss-calc`.

**Comment by evilebottnawi** [comment]
Fixed in original package. Just update your lock files.

**Comment by kelly-tock** [comment]
@evilebottnawi which package do we upgrade for this? `postcss-calc`?

**Comment by evilebottnawi** [comment]
@kelly-tock `postcss-calc`

**Comment by kelly-tock** [comment]
hmm...i'm still having issues. 

I upgraded `postcss-calc`
`postcss-calc@6.0.2`

stack trace:
```js
Error: Parse error on line 1:
env(safe-area-inset-
^
Expecting 'SUB', 'LPAREN', 'NESTED_CALC', 'NUMBER', 'CSS_VAR', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'PREFIX'
    at Parser.parseError (/Users/kelly/tock/admin/consumer/node_modules/reduce-css-calc/dist/parser.js:160:21)
    at Parser.parse (/Users/kelly/tock/admin/consumer/node_modules/reduce-css-calc/dist/parser.js:226:22)
    at /Users/kelly/tock/admin/consumer/node_modules/reduce-css-calc/dist/index.js:35:30
    at walk (/Users/kelly/tock/admin/consumer/node_modules/postcss-value-parser/lib/walk.js:15:13)
    at ValueParser.walk (/Users/kelly/tock/admin/consumer/node_modules/postcss-value-parser/lib/index.js:18:5)
    at exports.default (/Users/kelly/tock/admin/consumer/node_modules/reduce-css-calc/dist/index.js:29:51)
    at transformValue (/Users/kelly/tock/admin/consumer/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/lib/transform.js:24:45)
    at exports.default (/Users/kelly/tock/admin/consumer/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/lib/transform.js:54:100)
    at /Users/kelly/tock/admin/consumer/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/index.js:28:52
    at /Users/kelly/tock/admin/consumer/node_modules/postcss/lib/container.js:144:26
    at Rule.each (/Users/kelly/tock/admin/consumer/node_modules/postcss/lib/container.js:110:22)
    at Rule.walk (/Users/kelly/tock/admin/consumer/node_modules/postcss/lib/container.js:143:21)
    at /Users/kelly/tock/admin/consumer/node_modules/postcss/lib/container.js:146:32
    at Root.each (/Users/kelly/tock/admin/consumer/node_modules/postcss/lib/container.js:110:22)
    at Root.walk (/Users/kelly/tock/admin/consumer/node_modules/postcss/lib/container.js:143:21)
    at /Users/kelly/tock/admin/consumer/node_modules/cssnano-preset-default/node_modules/postcss-calc/dist/index.js:25:9
    at initializePlugin (/Users/kelly/tock/admin/consumer/node_modules/cssnano/dist/index.js:35:51)
```

example css:
```
  margin-bottom: env(safe-area-inset-bottom);
  margin-top: env(safe-area-inset-top);
```
i'm using this all in the context of:

https://www.npmjs.com/package/mini-css-extract-plugin

**Comment by kelly-tock** [comment]
any ideas on this?  I realized this is being used by optimize-css-assets-webpack-plugin and not mini-css-extract.

**Comment by andyjansson** [comment]
Hi. I'm busy today (birthday celebration), but I'll look into releasing it this weekend.

**Comment by evilebottnawi** [comment]
@andyjansson Great! Have a good birthday celebration :star:

**Comment by kelly-tock** [comment]
@andyjansson looks like maybe you just released?

**Comment by kelly-tock** [comment]
looks like the other culprit for my case anyway is `cssnano-preset-default` which has a dep on `postcss-calc` of `^6.0.0`. ugh...

**Comment by demosglok** [comment]
`.video {
    width: 100%;
    height: calc(width*56.25);
  }`
also produces same error. post-css-calc breaks on "width" as it doesn't understand what is it
