### ISSUE TITLE
mergeRules should not merge unknown pseudo selectors

### ISSUE THREAD

**Issue by fracmak** [cssnano/cssnano#642]
It appears that if a browser (tested in Chrome 69, Firefox 60, Safari 12, Edge 16) does not recognize a pseudo selector, it drops the entire selector, including any combined selectors. 

Example:

https://codepen.io/anon/pen/ZqxNEq

![image](https://user-images.githubusercontent.com/378178/47170937-6e962200-d2d5-11e8-9664-35889a16eb5f.png)

**Comment by saulhardman** [comment]
I've recently come across this issue myself and I'm wondering if it's currently possible to disable optimisations on a line-by-line basis? E.g. like ESLint's `// eslint-disable-line` comment format.

**Comment by evilebottnawi** [comment]
@saulhardman no, it is hard to implement using comments, but PR welcome

**Comment by saulhardman** [comment]
@evilebottnawi I figured as much, thanks for your response 👍

**Comment by ben-eb** [comment]
@evilebottnawi We have a system for handling mergeable pseudo elements here:

https://github.com/cssnano/cssnano/blob/master/packages/postcss-merge-rules/src/lib/ensureCompatibility.js#L13

Perhaps this should be changed; currently this list prevents a merge for known pseudo selectors, but allows unknown ones through. If we only allow a merge on known pseudo selectors, we will have less bug reports on broken behaviour and hopefully more reports of acceptable pseudo selector merging.

In any case this is a matter of adding `':focus-visible': 'css-focus-visible'` to that list.

**Comment by evilebottnawi** [comment]
Good idea, can you take care about this?

**Comment by ben-eb** [comment]
@evilebottnawi Probably easier if we fix the immediate bug and then can look into changing behaviour later?

**Comment by evilebottnawi** [comment]
Sounds good, need open issue about this or update currently

**Comment by felixfbecker** [comment]
`:focus-visible` is now on the list (so rules using it will be merged), but not supported by any browsers other than Firefox, meaning CSSNano currently breaks Chrome when e.g. using a `focus-visible` polyfill that creates duplicate rules for `:focus-visible` and a polyfilled `.focus-visible` class. Is there a way to instruct CSSNano to not consider `:focus-visible` "supported"?

**Comment by anikethsaha** [comment]
are you using the nightly ?

cause this has been fixed in https://github.com/cssnano/cssnano/pull/882 but not released yet.

**Comment by anikethsaha** [comment]
> :focus-visible is now on the list (so rules using it will be merged)

no it wont (in the master). ref this https://github.com/cssnano/cssnano/blob/a4b38cbfaf/packages/postcss-merge-rules/src/__tests__/index.js#L790

**Comment by felixfbecker** [comment]
Ah, I was confused, I understand the issue now (before all unknown selectors were merged, and `:focus-visible` was unknown, but now both unknown selectors are no longer merged and `:focus-visible` is known now, but will still not be merged depending on CanIUse/browserslist data). Thanks.
Is there an ETA for the release?

**Comment by anikethsaha** [comment]
once https://github.com/cssnano/cssnano/pull/954 is done. 


In the meantime use [`cssnano@nightly`](https://github.com/cssnano/cssnano-nightly). that is up to date with the master and pretty stable.
