### ISSUE TITLE
postcss-normalize-whitespace breaks 

### ISSUE THREAD

**Issue by bugzpodder** [cssnano/cssnano#661]
postcss-normalize-whitespace breaks production build using dart-css only.

I am using create-react-app 2.0 config, which uses OptimizeCSSAssetsPlugin in production build.
So it uses css-nano with cssnano-preset-default.  I noticed it breaks production build if I switch from node-sass (works fine) to dart-sass (breaks).  I disabled each rule until I found the culprit and it seems postcss-normalize-whitespace breaks.

Here are the prettified diff between the two css files generated, can't tell what lines went wrong.
`-` represents the correct css, + becomes incorrect.
```

@@ -1882,3 +1882,3 @@
 blockquote small:before {
-    content: "\2014   \A0"
+    content: "\2014\A0"
 }
@@ -1909,3 +1909,3 @@
 blockquote.pull-right small:after {
-    content: "\A0   \2014"
+    content: "\A0\2014"
 }
@@ -3294,4 +3294,3 @@
 input[type=radio] {
-    margin: 4px 0 0;
-    margin-top: 1px\9;
+    margin: 1px \ 0 0;
     line-height: normal
@@ -3410,14 +3409,6 @@
 
-    .input-group-sm>.input-group-btn>input.btn[type=date],
-    .input-group-sm>.input-group-btn>input.btn[type=datetime-local],
-    .input-group-sm>.input-group-btn>input.btn[type=month],
-    .input-group-sm>.input-group-btn>input.btn[type=time],
-    .input-group-sm>input.form-control[type=date],
-    .input-group-sm>input.form-control[type=datetime-local],
-    .input-group-sm>input.form-control[type=month],
-    .input-group-sm>input.form-control[type=time],
-    .input-group-sm>input.input-group-addon[type=date],
-    .input-group-sm>input.input-group-addon[type=datetime-local],
-    .input-group-sm>input.input-group-addon[type=month],
-    .input-group-sm>input.input-group-addon[type=time],
+    .input-group-sm>.input-group-btn>input[type=date].btn,
+    .input-group-sm>.input-group-btn>input[type=datetime-local].btn,
+    .input-group-sm>.input-group-btn>input[type=month].btn,
+    .input-group-sm>.input-group-btn>input[type=time].btn,
     .input-group-sm input[type=date],
@@ -3433,14 +3424,6 @@
 
-    .input-group-lg>.input-group-btn>input.btn[type=date],
-    .input-group-lg>.input-group-btn>input.btn[type=datetime-local],
-    .input-group-lg>.input-group-btn>input.btn[type=month],
-    .input-group-lg>.input-group-btn>input.btn[type=time],
-    .input-group-lg>input.form-control[type=date],
-    .input-group-lg>input.form-control[type=datetime-local],
-    .input-group-lg>input.form-control[type=month],
-    .input-group-lg>input.form-control[type=time],
-    .input-group-lg>input.input-group-addon[type=date],
-    .input-group-lg>input.input-group-addon[type=datetime-local],
-    .input-group-lg>input.input-group-addon[type=month],
-    .input-group-lg>input.input-group-addon[type=time],
+    .input-group-lg>.input-group-btn>input[type=date].btn,
+    .input-group-lg>.input-group-btn>input[type=datetime-local].btn,
+    .input-group-lg>.input-group-btn>input[type=month].btn,
+    .input-group-lg>.input-group-btn>input[type=time].btn,
     .input-group-lg input[type=date],
@@ -3484,3 +3467,3 @@
     margin-left: -20px;
-    margin-top: 4px\9
+    margin-top: 4px \
 }
@@ -3564,6 +3547,6 @@
 
-.input-group-sm>.input-group-btn>select.btn[multiple],
+.input-group-sm>.input-group-btn>select[multiple].btn,
 .input-group-sm>.input-group-btn>textarea.btn,
-.input-group-sm>select.form-control[multiple],
-.input-group-sm>select.input-group-addon[multiple],
+.input-group-sm>select[multiple].form-control,
+.input-group-sm>select[multiple].input-group-addon,
 .input-group-sm>textarea.form-control,
@@ -3620,6 +3603,6 @@
 
-.input-group-lg>.input-group-btn>select.btn[multiple],
+.input-group-lg>.input-group-btn>select[multiple].btn,
 .input-group-lg>.input-group-btn>textarea.btn,
-.input-group-lg>select.form-control[multiple],
-.input-group-lg>select.input-group-addon[multiple],
+.input-group-lg>select[multiple].form-control,
+.input-group-lg>select[multiple].input-group-addon,
 .input-group-lg>textarea.form-control,
@@ -4490,4 +4473,3 @@
     vertical-align: middle;
-    border-top: 4px dashed;
-    border-top: 4px solid\9;
+    border-top: 4px solid \;
     border-right: 4px solid transparent;
@@ -4624,4 +4606,3 @@
     border-top: 0;
-    border-bottom: 4px dashed;
-    border-bottom: 4px solid\9;
+    border-bottom: 4px solid \;
     content: ""
@@ -5184,5 +5165,3 @@
 .nav-tabs-justified>.active>a:hover,
-.nav-tabs.nav-justified>.active>a,
-.nav-tabs.nav-justified>.active>a:focus,
-.nav-tabs.nav-justified>.active>a:hover {
+.nav-tabs.nav-justified>.active>a {
     border: 1px solid #ddd
@@ -5201,5 +5180,3 @@
     .nav-tabs-justified>.active>a:hover,
-    .nav-tabs.nav-justified>.active>a,
-    .nav-tabs.nav-justified>.active>a:focus,
-    .nav-tabs.nav-justified>.active>a:hover {
+    .nav-tabs.nav-justified>.active>a {
         border-bottom-color: #fff

@@ -7938,3 +7915,3 @@
     cursor: pointer;
-    background-color: #000\9;
+    background-color: #000 \;
     background-color: transparent
@@ -15657,2 +15634,2 @@

```

**Comment by evilebottnawi** [comment]
Problem in `css-loader` and already fixed in master (will be release today)

**Comment by evilebottnawi** [comment]
Also please create issue with examples before and after in future, no need copy paste in issue because it is hard to read and debug

**Comment by bugzpodder** [comment]
Unfortunately css-loader 2.0 still breaks (I used yarn resolution to install the new version).
I'll look at it later at some point to see if I can come up with something.

**Comment by evilebottnawi** [comment]
@bugzpodder what is broken in `css-loader@2`?

**Comment by bugzpodder** [comment]
@evilebottnawi  Sorry, I meant my build is still not displaying the right css with css-loader@2 so css-loader@2 is not the source of the bug.  And it seems to be a quirk with dart-sass + css-loader + css-nano + postcss-normalize-whitespace.  The build will work if I replace dart-sass with node+sass, or disable postcss-normalize-whitespace.   I will investigate and try to come up with a repo (but the css itself is 10k lines because of bootstrap) so we'll see.

**Comment by evilebottnawi** [comment]
@bugzpodder feel free to create new issue or reopen with examples

**Comment by bugzpodder** [comment]
I ended up tracking down the issue to this particular file in bootstrap scss:
https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_forms.scss
taking it out make everything work.  So I am just going to remove this file and call it a day.  Leaving it here as a reference in case anyone else runs into a similar issue.

**Comment by evilebottnawi** [comment]
@bugzpodder what are broken in this minified file?
